# Generated by Django 5.1.7 on 2025-03-22 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = []

    # Define the model in state_operations
    state_operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=55, unique=True)),
                ("abbreviation", models.CharField(max_length=10, unique=True)),
                (
                    "testament",
                    models.CharField(choices=[("OT", "Old Testament"), ("NT", "New Testament")], max_length=2),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        help_text="Position in the ordering of the Bible (1-66)",
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(1, message="Value must be at least 1"),
                            django.core.validators.MaxValueValidator(66, message="Value cannot be greater than 66"),
                        ],
                    ),
                ),
                (
                    "chapters",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(
                                150, message="There's no Book of the Bible with more than 150 chapters"
                            )
                        ]
                    ),
                ),
                ("title_and_author", models.TextField(blank=True)),
                ("date_and_occasion", models.TextField(blank=True)),
                ("characteristics_and_themes", models.TextField(blank=True)),
                ("christ_in_book", models.TextField(blank=True)),
                ("timeline", models.JSONField(blank=True, default=dict)),
                ("outline", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["number"],
                "db_table": "core_book",  # Keep the old table name
            },
        ),
    ]

    operations = [
        # Use SeparateDatabaseAndState to tell Django we don't want to create the table,
        # just update the state in the Django ORM
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations,
        ),
    ]
