# Generated by Django 5.1.7 on 2025-03-22 14:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        # We're using SeparateDatabaseAndState to keep the tables but delete the model from Django's ORM
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                # Deleting the Book model (now in bible app)
                migrations.DeleteModel(
                    name="Book",
                ),
                # Deleting the Note model (now in notes app)
                migrations.DeleteModel(
                    name="Note",
                ),
                # Deleting the NoteType model (now in notes app)
                migrations.DeleteModel(
                    name="NoteType",
                ),
            ],
        ),
    ]
