# Generated by Django 5.1.7 on 2025-03-22 15:00

import django.db.models.deletion
import milk2meat.core.utils.validators
import milk2meat.notes.models
import taggit.managers
import upload_validator
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bible", "0001_initial"),
        ("core", "0001_initial"),
        ("taggit", "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NoteType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=255)),
                ("content", models.TextField(blank=True)),
                (
                    "upload",
                    models.FileField(
                        blank=True,
                        help_text="You could upload handwritten notes from iPad as PDF or image",
                        null=True,
                        upload_to=milk2meat.notes.models.user_note_upload_path,
                        validators=[
                            upload_validator.FileTypeValidator(
                                allowed_types=[
                                    "image/jpeg",
                                    "image/png",
                                    "image/webp",
                                    "image/bmp",
                                    "image/svg+xml",
                                    "application/pdf",
                                    "application/msword",
                                    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                                    "application/rtf",
                                    "application/vnd.oasis.opendocument.text",
                                    "application/vnd.ms-excel",
                                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                                    "application/vnd.oasis.opendocument.spreadsheet",
                                    "text/csv",
                                    "application/vnd.ms-powerpoint",
                                    "application/vnd.openxmlformats-officedocument.presentationml.presentation",
                                    "application/vnd.oasis.opendocument.presentation",
                                ]
                            ),
                            milk2meat.core.utils.validators.FileSizeValidator(),
                        ],
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="notes", to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("referenced_books", models.ManyToManyField(blank=True, related_name="notes", to="bible.book")),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="core.UUIDTaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "note_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="notes", to="notes.notetype"
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-created_at"],
                "constraints": [models.UniqueConstraint(fields=("slug", "owner"), name="unique_owner_slug")],
            },
        ),
    ]
