# Generated by Django 5.1.7 on 2025-03-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bible", "0001_initial"),
        ("notes", "0001_initial"),
    ]

    operations = [
        # Add the M2M relationship between notes and books
        # This doesn't create a new table, just uses the existing one
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="note",
                    name="referenced_books",
                    field=models.ManyToManyField(blank=True, related_name="notes", to="bible.book"),
                ),
            ],
        ),
    ]
